import { StyleSheet } from 'react-native';
import { theme } from './theme';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    gradient: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: theme.spacing.xl,
        paddingBottom: 10,
    },
    title: {
        fontSize: theme.fontSize.huge,
        fontWeight: 'bold',
        color: theme.colors.white,
        textShadowColor: 'rgba(220, 38, 38, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
        flex: 1,
        textAlign: 'center',
        marginRight: 44, // Compensate for language button width
    },
    languageButton: {
        padding: 10,
        borderRadius: theme.borderRadius.medium,
        backgroundColor: theme.colors.primaryOpacity,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorder,
    },
    content: {
        flex: 1,
        padding: theme.spacing.xl,
    },
    radioGroup: {
        flexDirection: 'row',
        backgroundColor: theme.colors.whiteOpacity,
        borderRadius: theme.borderRadius.large,
        padding: theme.spacing.xs,
        marginBottom: theme.spacing.xl,
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
    },
    radioButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: theme.spacing.md + 2,
        borderRadius: theme.borderRadius.medium,
        backgroundColor: 'transparent',
        marginHorizontal: 2,
    },
    radioButtonFirst: {
        marginLeft: 0,
    },
    radioButtonLast: {
        marginRight: 0,
    },
    radioButtonActive: {
        backgroundColor: theme.colors.primary,
        ...theme.shadows.primary,
    },
    radioText: {
        color: theme.colors.gray,
        marginLeft: theme.spacing.sm,
        fontSize: theme.fontSize.medium,
        fontWeight: '600',
    },
    radioTextActive: {
        color: theme.colors.white,
    },
    checkboxContainer: {
        alignItems: 'center',
        marginBottom: theme.spacing.xl,
    },
    checkbox: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.medium,
        backgroundColor: theme.colors.whiteOpacity,
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
    },
    checkboxBox: {
        width: 22,
        height: 22,
        borderRadius: theme.borderRadius.small,
        borderWidth: 2,
        borderColor: theme.colors.gray,
        backgroundColor: 'transparent',
        marginRight: theme.spacing.md,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxBoxChecked: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    checkmark: {
        color: theme.colors.white,
        fontSize: theme.fontSize.small,
        fontWeight: 'bold',
    },
    checkboxText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
        fontWeight: '500',
    },
    searchContainer: {
        position: 'relative',
        marginBottom: 10,
    },
    searchInput: {
        backgroundColor: theme.colors.whiteOpacity,
        borderRadius: theme.borderRadius.medium,
        padding: theme.spacing.lg,
        paddingRight: 50,
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    searchIcon: {
        position: 'absolute',
        right: theme.spacing.lg,
        top: 18,
    },
    moodDropdown: {
        backgroundColor: theme.colors.whiteOpacity,
        borderRadius: theme.borderRadius.medium,
        padding: theme.spacing.lg,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    moodDropdownText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
    },
    placeholder: {
        color: theme.colors.gray,
    },
    autocompleteContainer: {
        backgroundColor: 'rgba(0, 0, 0, 0.95)',
        borderRadius: theme.borderRadius.medium,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
        overflow: 'hidden',
    },
    autocompleteItem: {
        padding: theme.spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.whiteBorder,
    },
    autocompleteText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
    },
    disabledText: {
        color: theme.colors.gray,
    },
    selectedContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: theme.spacing.xl,
    },
    selectedItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(220, 38, 38, 0.15)',
        borderRadius: theme.borderRadius.xlarge,
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.lg,
        margin: theme.spacing.xs,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorder,
    },
    selectedText: {
        color: theme.colors.white,
        marginRight: theme.spacing.sm,
        fontSize: theme.fontSize.medium,
        fontWeight: '500',
    },
    recommendButton: {
        marginBottom: theme.spacing.xxl,
        backgroundColor: theme.colors.primary,
        borderRadius: 14,
        padding: 18,
        alignItems: 'center',
        ...theme.shadows.primary,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorder,
    },
    buttonText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.xlarge,
        fontWeight: 'bold',
    },
    recommendationsContainer: {
        marginBottom: theme.spacing.xxl,
    },
    recommendationsTitle: {
        fontSize: theme.fontSize.xxxlarge,
        fontWeight: 'bold',
        color: theme.colors.white,
        marginBottom: theme.spacing.xl,
        textAlign: 'center',
    },
    songCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        borderRadius: theme.borderRadius.xlarge,
        padding: theme.spacing.xl,
        marginBottom: theme.spacing.md,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        ...theme.shadows.card,
    },
    songCardContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    songImageContainer: {
        position: 'relative',
        marginRight: theme.spacing.lg,
    },
    coverImage: {
        width: 70,
        height: 70,
        borderRadius: theme.borderRadius.large,
    },
    playOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        borderRadius: theme.borderRadius.large,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 0.8,
    },
    songInfo: {
        flex: 1,
    },
    songName: {
        color: theme.colors.white,
        fontSize: 17,
        fontWeight: 'bold',
        marginBottom: 6,
    },
    artistName: {
        color: theme.colors.lightGray,
        fontSize: 15,
        marginBottom: theme.spacing.sm,
    },
    songMeta: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    songIndex: {
        color: theme.colors.primary,
        fontSize: theme.fontSize.small,
        fontWeight: 'bold',
        marginRight: theme.spacing.md,
        minWidth: 24,
    },
    popularityIndicator: {
        flex: 1,
        height: 3,
        backgroundColor: theme.colors.whiteBorder,
        borderRadius: 2,
        overflow: 'hidden',
    },
    popularityBar: {
        height: '100%',
        backgroundColor: theme.colors.primary,
        borderRadius: 2,
    },
    favoriteButton: {
        padding: theme.spacing.sm,
        borderRadius: theme.borderRadius.xlarge,
        backgroundColor: theme.colors.whiteOpacity,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    welcomeModal: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.xxlarge,
        padding: theme.spacing.xxl,
        width: '90%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: theme.colors.primaryBorder,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    welcomeHeader: {
        alignItems: 'center',
        marginBottom: theme.spacing.xl,
    },
    welcomeTitle: {
        color: theme.colors.white,
        fontSize: theme.fontSize.xxxlarge,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: theme.spacing.md,
        marginBottom: theme.spacing.sm,
    },
    welcomeSubtitle: {
        color: theme.colors.primary,
        fontSize: theme.fontSize.large,
        fontWeight: '600',
        textAlign: 'center',
    },
    welcomeDescription: {
        color: theme.colors.darkGray,
        fontSize: theme.fontSize.large,
        textAlign: 'center',
        marginBottom: theme.spacing.xl,
        lineHeight: 22,
    },
    stepsContainer: {
        marginBottom: theme.spacing.xxl,
    },
    stepText: {
        color: theme.colors.white,
        fontSize: 15,
        marginBottom: theme.spacing.md,
        paddingLeft: 10,
        lineHeight: 20,
    },
    getStartedButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: theme.borderRadius.large,
        padding: 18,
        alignItems: 'center',
        ...theme.shadows.primary,
    },
    getStartedText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.xlarge,
        fontWeight: 'bold',
    },
    welcomeCheckboxContainer: {
        alignItems: 'center',
        marginBottom: theme.spacing.xl,
    },
    welcomeCheckbox: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
        paddingHorizontal: theme.spacing.lg,
        borderRadius: theme.borderRadius.medium,
        backgroundColor: theme.colors.whiteOpacity,
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
    },
    welcomeCheckboxBox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: theme.colors.gray,
        backgroundColor: 'transparent',
        marginRight: theme.spacing.md,
        alignItems: 'center',
        justifyContent: 'center',
    },
    welcomeCheckboxBoxChecked: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    welcomeCheckmark: {
        color: theme.colors.white,
        fontSize: theme.fontSize.small,
        fontWeight: 'bold',
    },
    welcomeCheckboxText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.medium,
        fontWeight: '500',
    },
    moodModal: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.xlarge,
        padding: theme.spacing.xl,
        width: '80%',
        maxHeight: '70%',
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
    },
    moodItem: {
        padding: theme.spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.whiteBorder,
    },
    moodItemText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.xlarge,
        textAlign: 'center',
    },
    closeButton: {
        marginTop: theme.spacing.xl,
        padding: theme.spacing.lg,
        backgroundColor: theme.colors.primary,
        borderRadius: theme.borderRadius.medium,
        alignItems: 'center',
    },
    closeButtonText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
        fontWeight: 'bold',
    },
    languageModal: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.borderRadius.xlarge,
        padding: theme.spacing.xl,
        width: '70%',
        borderWidth: 1,
        borderColor: theme.colors.whiteBorder,
    },
    languageModalTitle: {
        color: theme.colors.white,
        fontSize: theme.fontSize.xxlarge,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: theme.spacing.xl,
    },
    languageOption: {
        padding: theme.spacing.lg,
        borderRadius: theme.borderRadius.medium,
        marginBottom: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
    },
    languageOptionSelected: {
        backgroundColor: theme.colors.primary,
    },
    languageOptionText: {
        color: theme.colors.white,
        fontSize: theme.fontSize.large,
        fontWeight: '600',
    },
});

export default styles;
