export const theme = {
    colors: {
        primary: '#dc2626',
        primaryOpacity: 'rgba(220, 38, 38, 0.1)',
        primaryBorder: 'rgba(220, 38, 38, 0.3)',
        background: '#000000',
        surface: '#1a1a1a',
        white: '#fff',
        whiteOpacity: 'rgba(255, 255, 255, 0.05)',
        whiteBorder: 'rgba(255, 255, 255, 0.1)',
        gray: '#666',
        lightGray: '#999',
        darkGray: '#ccc',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        xxl: 30,
    },
    borderRadius: {
        small: 6,
        medium: 12,
        large: 16,
        xlarge: 20,
        xxlarge: 24,
    },
    fontSize: {
        small: 12,
        medium: 14,
        large: 16,
        xlarge: 18,
        xxlarge: 20,
        xxxlarge: 24,
        huge: 28,
    },
    shadows: {
        primary: {
            shadowColor: '#dc2626',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.4,
            shadowRadius: 12,
            elevation: 8,
        },
        card: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.3,
            shadowRadius: 16,
            elevation: 8,
        },
    },
};
